services:
  db:
    image: postgres:15-alpine
    container_name: sedentary_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sedentary_data
    ports:
      - "5434:5432"
    volumes:
      - sedentary_postgres_data:/var/lib/postgresql/data

  
  redis:
    image: redis:7-alpine
    container_name: sedentary_redis
    ports:
      - "6379:6379"
  
volumes:
  sedentary_postgres_data: